name: Deploy Vue with Vite to GitHub Pages

on:
  push:
    branches: [ "develop" ]
  # pull_request:
  #   branches: [ "develop" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

      - name: Build da aplicação
        run: npm run build

      - name: Deploy para GitHub Pages
        uses: skywarth/vite-github-pages-deployer@v1.4.0
        with:
          build_directory: dist  # Certifique-se de que este é o diretório correto
          branch: gh-pages
